### ISSUE TITLE
Incorrect commit author name exported

### ISSUE THREAD

**Issue by chibatching** [bitrise-steplib/steps-git-clone#89] opened 2019-03-01 02:56 UTC
On our build for pull request, git-clone step exports incorrect commit author's email and name.

```
+------------------------------------------------------------------------------+

| (1) git-clone                                                                |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 4.0.14                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-02-26T23:50:29-08:00                                              |
+------------------------------------------------------------------------------+
|                                                                              |
config:
- RepositoryURL: git@github.com:tokubai/ios-bargain.git
- CloneIntoDir: /Users/vagrant/git
- Commit: 083b961193f657666a94466c4d2b1cce90b3369f
- Tag: 
- Branch: fix_launch_from_notification
- BranchDest: master
- PRID: 3689
- PRRepositoryURL: git@github.com:tokubai/ios-bargain.git
- PRMergeBranch: pull/3689/merge
- ResetRepository: false
- CloneDepth: 0
- BuildURL: https://app.bitrise.io/build/6d0a7671c2b1cdc0
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
git "init"
Initialized empty Git repository in /Users/vagrant/git/.git/
git "remote" "add" "origin" "git@github.com:tokubai/ios-bargain.git"
git "fetch" "origin" "master"
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
From github.com:tokubai/ios-bargain
 * branch                master     -> FETCH_HEAD
 * [new branch]          master     -> origin/master
git "checkout" "master"
Already on 'master'
Branch 'master' set up to track remote branch 'master' from 'origin'.
git "merge" "origin/master"
Already up to date.
commit hash: 190060f35e606915ab34da72e8362a0874915577
git "fetch" "origin" "fix_launch_from_notification"
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
From github.com:tokubai/ios-bargain
 * branch                fix_launch_from_notification -> FETCH_HEAD
 * [new branch]          fix_launch_from_notification -> origin/fix_launch_from_notification
git "merge" "083b961193f657666a94466c4d2b1cce90b3369f"
Merge made by the 'recursive' strategy.
 .../notification/RemoteNotificationManager.swift   | 36 +++++++++++++---------
 1 file changed, 21 insertions(+), 15 deletions(-)
git "submodule" "update" "--init" "--recursive"
git "checkout" "--detach"
HEAD is now at e606fa0e2 Merge commit '083b961193f657666a94466c4d2b1cce90b3369f'
Exporting git logs
=> GIT_CLONE_COMMIT_AUTHOR_NAME
   value: J. Doe (https://www.git-tower.com/learn/git/faq/change-author-name-email)
=> GIT_CLONE_COMMIT_AUTHOR_EMAIL
   value: please-set-your-email@bitrise.io
=> GIT_CLONE_COMMIT_COMMITER_NAME
   value: J. Doe (https://www.git-tower.com/learn/git/faq/change-author-name-email)
=> GIT_CLONE_COMMIT_COMMITER_EMAIL
   value: please-set-your-email@bitrise.io
=> GIT_CLONE_COMMIT_HASH
   value: e606fa0e2425187fef1e8d5b4c33ffc06252726b
=> GIT_CLONE_COMMIT_MESSAGE_SUBJECT
   value: Merge commit '083b961193f657666a94466c4d2b1cce90b3369f'
=> GIT_CLONE_COMMIT_MESSAGE_BODY
   value: 
=> GIT_CLONE_COMMIT_COUNT
   value: 9307
Success
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | git-clone                                                     | 13 sec   |
+---+---------------------------------------------------------------+----------+
```

Original commit hash `083b961193f657666a94466c4d2b1cce90b3369f` has correct author and email.
And commit `e606fa0e2425187fef1e8d5b4c33ffc06252726b` is not exists because it may be created by this step.
Could you export original commit's author and message?

**Comment by bitce** [comment] 2019-03-01 11:48
Hi @chibatching,

You're seeing this author because this is a default value in your build. The name also contains the link in which you can find out how to set your git user for yourself. Please see: 
https://www.git-tower.com/learn/git/faq/change-author-name-email

**Comment by chibatching** [comment] 2019-03-01 13:12
Of course, I and team members know and set the git user.
And git log show the author of the original commit.
For example, I can find the author name in git log command (sorry, name and email are masked).

```
$ git log 083b961193f657666a94466c4d2b1cce90b3369f
commit 083b961193f657666a94466c4d2b1cce90b3369f
Author: xxxxxxxxxx <xxxxx-xxxxxxxxx@gmail.com>
Date:   Wed Feb 27 14:18:08 2019 +0900

    Fix fallback.
```

This happens only pull request triggered builds. 
Push trigger builds exports correct author and message.

**Comment by bitce** [comment] 2019-03-01 13:13
Oh I see! Could you send us a link to the app and allow Support Access?

**Comment by chibatching** [comment] 2019-03-01 13:16
Ok, I see. But how can I send you a link? Here?

**Comment by bitce** [comment] 2019-03-01 13:20
Sure! If you have security concerns (although the URL itself shouldn't be anything to worry about, since even we can't access your app without Support Access) you can also contact us about this on our on-site chat or via e-mail at letsconnect@bitrise.io

**Comment by chibatching** [comment] 2019-03-01 13:21
This is a link of our app https://app.bitrise.io/app/610196c6789e7031
Thank you!

**Comment by fehersanyi-bitrise** [comment] 2019-03-04 10:20
Hy @chibatching 

I checked it but I'm not really sure where the step gets the author 🤔
and I see various values there, I don't know if the PR-s last committer or the one who initiated the PR gets there.

**Comment by Mazyod** [comment] 2019-05-27 22:56
Hello, we are affected by this as well. The problem is very simple. The values are exported *after* the merge is made, and that leads to incorrect git info being exported.

Here is the output, and as you can see, due to the manual merge, the exported values are taken **after** the merge, so they represent the merge commit, which isn't useful to us when we need to report this information back through slack, for example. This problem only manifests if the PR is behind the target branch, since that would lead to the manual merge, and that would lead to the problematic git info.

```
+------------------------------------------------------------------------------+

| (1) Clone Repository                                                         |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 4.0.14                                                              |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-05-27T21:57:04Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
config:
- RepositoryURL: git@bitbucket.org:xxx/xxx.git
- CloneIntoDir: /Users/vagrant/git
- Commit: 19195105782c
- Tag: 
- Branch: tests/final-fixes
- BranchDest: develop
- PRID: 2190
- PRRepositoryURL: git@bitbucket.org:xxx/xxx.git
- PRMergeBranch: 
- ResetRepository: false
- CloneDepth: 0
- BuildURL: https://app.bitrise.io/build/00386f39c8290979
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true
git "init"
Initialized empty Git repository in /Users/vagrant/git/.git/
git "remote" "add" "origin" "git@bitbucket.org:xxx/xxx.git"
git "fetch" "origin" "develop"
Warning: Permanently added 'bitbucket.org,18.205.93.1' (RSA) to the list of known hosts.
From bitbucket.org:xxx/xxx
 * branch                develop    -> FETCH_HEAD
 * [new branch]          develop    -> origin/develop
git "checkout" "develop"
Switched to a new branch 'develop'
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
git "merge" "origin/develop"
Already up to date.
commit hash: c5be7458acb85be8c26008643e1f5693a5eeafcb
git "fetch" "origin" "tests/final-fixes"
Warning: Permanently added 'bitbucket.org,18.205.93.2' (RSA) to the list of known hosts.
From bitbucket.org:xxx/xxx
 * branch                tests/final-fixes -> FETCH_HEAD
 * [new branch]          tests/final-fixes -> origin/tests/final-fixes
git "merge" "19195105782c"
[ ... redacted ... ]
 8 files changed, 90 insertions(+), 119 deletions(-)
[ ... redacted ... ]
git "submodule" "update" "--init" "--recursive"
[ ... redacted ... ]
git "checkout" "--detach"
HEAD is now at 1289c0b48 Merge commit '19195105782c' into develop
Exporting git logs
=> GIT_CLONE_COMMIT_HASH
   value: 1289c0b4822722ed8178e9f33e51a3dd3e7e6110
=> GIT_CLONE_COMMIT_MESSAGE_SUBJECT
   value: Merge commit '19195105782c' into develop
=> GIT_CLONE_COMMIT_MESSAGE_BODY
   value: 
=> GIT_CLONE_COMMIT_AUTHOR_NAME
   value: J. Doe (https://devcenter.bitrise.io/builds/setting-your-git-credentials-on-build-machines/)
=> GIT_CLONE_COMMIT_AUTHOR_EMAIL
   value: please-set-your-email@bitrise.io
=> GIT_CLONE_COMMIT_COMMITER_NAME
   value: J. Doe (https://devcenter.bitrise.io/builds/setting-your-git-credentials-on-build-machines/)
=> GIT_CLONE_COMMIT_COMMITER_EMAIL
   value: please-set-your-email@bitrise.io
=> GIT_CLONE_COMMIT_COUNT
   value: 11809
```

**Comment by fehersanyi-bitrise** [comment] 2019-05-28 08:09
Hello @Mazyod 

this is probably because the git user is not set up properly locally on the dev machines so github does not know the author 🙃
this can be easily set up via the terminal like this:
```
$ git config --global user.name "John Doe"
$ git config --global user.email johndoe@example.com
```

**Comment by fehersanyi-bitrise** [comment] 2019-05-28 09:20
@Mazyod 

You know that the step gets these values from the webhook GitHub sends out, these values are not decided by us. This is what been sent to us, this is what we display 🙃
Bitrise does not change, nor sets these at all.

**Comment by bitce** [comment] 2019-05-28 10:14
Hey @chibatching!

Sorry for the inconvenience, could you enable Support Access again? Just to ensure we're certain what's going on in the build and that we can inform you accordingly :)

**Comment by Mazyod** [comment] 2019-05-28 11:16
@fehersanyi-bitrise the user info is properly set, as I mentioned it only manifests when a merge commit is created on bitrise, and the user config on bitrise is not grabbing that from the PR, if that was the intention. Although, regardless of the author, please see the commit hash and commit message, it's also wrong since it is referring to the merge commit made on bitrise.

P.S. we are using bitbucket

**Comment by chibatching** [comment] 2019-05-29 02:28
@bitce 

Hi, I enabled support access again. Please check it!

**Comment by chibatching** [comment] 2019-06-07 07:01
@bitce 
Has there been any update about this issue?

**Comment by bitce** [comment] 2019-06-07 09:51
@chibatching

Unfortunately nothing specific we can provide, the team is still reviewing this situation, we will absolutely make sure to let you know here once we can provide an update.

**Comment by Unknoob** [comment] 2019-12-04 21:37
We are also experiencing this issue. Bitrise randomly fails to get the correct `GIT_AUTHOR` for our builds.

**Comment by fchristysen** [comment] 2019-12-18 17:19
Hi, was facing the same issue here. I think the information like commit hash, author, and message are available through .git folder. But as @Mazyod says above, it seems the value are exported after the merge during pull request workflow, since git clone step tries to merge base with target branch. After the merge, those git information are not from commit the devs made the pull request from.

**Comment by nickruddeni** [comment] 2020-07-10 06:23
This is still an issue. We sporadically get John joe as commit author. As mentioned above this is when the target branch is ahead of the pull request branch. It doesn’t happen when the target can be fast forwarded.

**Comment by rajgrailed** [comment] 2020-07-29 22:03
Chiming in, can confirm we're still having this problem.

**Comment by godrei** [comment] 2021-03-10 13:00
Hi everyone!

We are aware that the wait on this (and several others) issue had been long without much communication from our side, I'd like to apologize for that.


Regarding this issue, it seems the problem is that, in the case of Pull Request checkout, we export the final state's commit info.
This might different than the PR commit's info, as to reach the final state, in the case of a Pull Request, based on the PR checkout strategy we might call git merge, which can result in a new commit.

My proposal would be to modify the step in a way it exports the PR commit's info, (rather than the merged state's commit info), in case of a Pull Request checkout. Also, I suggest leaving Author related info empty as in case of an open PR the patch is not yet applied.

What do you think about this resolution?

**Comment by gobetti** [comment] 2021-05-27 17:40
@godrei if I understand correctly, you're proposing to add new environment variables (besides the existing `$GIT_CLONE_COMMIT_*`) that will point to the pre-merge commit. That would probably solve all concerns here, as the post-merge commit might not be relevant as often, but in case any existing setup is relying on it, keeping that behavior with new env vars would be a non-breaking change.

Thanks for your attention to this!

**Closed** 2021-07-15 08:13 UTC
