### ISSUE TITLE
4.1.0 broke generate-changelog step

### ISSUE THREAD

**Issue by jamie1192** [bitrise-steplib/steps-git-clone#145] opened 2021-03-16 23:54 UTC
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 4.1.0
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES 

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

We use the [generate-changelog](https://github.com/bitrise-steplib/steps-generate-changelog) step within our workflow to generate logs based off tags, but the last few days our releases have output changelogs from the checked out commit, all the way back to the **_very first commit_**.

The only thing I can see in the Bitrise build log that's changed is that `git-clone` step has been updated to `4.1.0`, and used to execute `git fetch`, but now instead executes `git fetch origin refs/heads/master`, resulting in no tags existing in the cloned project.

If this was intentional, this should have been a breaking change/major release.

### Bitrise info

- Build URL: https://app.bitrise.io/build/d86ce933b13ebae1#?tab=log
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: NO
 

<details>
  <pre>
+--------------------
| (1) git-clone@4                                                              
+--------------------
| id: git-clone                                                                
| version: 4.1.0                                                              
| collection: https://github.com/bitrise-io/bitrise-steplib.git       
| toolkit: go                                                                  
| time: 2021-03-16T22:58:44Z                                                   

Config:
- RepositoryURL: <REDACTED>
- CloneIntoDir: /Users/vagrant/git
- Commit: <REDACTED>
- Tag: 
- Branch: master
- BranchDest: 
- PRID: 0
- PRRepositoryURL: 
- PRMergeBranch: 
- ResetRepository: false
- CloneDepth: 0
- BuildURL: <REDACTED>
- BuildAPIToken: [REDACTED]
- UpdateSubmodules: true
- ManualMerge: true

$ git "init"

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /Users/vagrant/git/.git/

$ git "remote" "add" "origin" "<REDACTED>"

$ git "fetch" "origin" "refs/heads/master"
Warning: Permanently added 'bitbucket.org,<REDACTED>' (RSA) to the list of known hosts.
From ssh://bitbucket.org/<REDACTED>/<REDACTED>
 * branch            master     -> FETCH_HEAD
 * [new branch]      master     -> origin/master

$ git "checkout" "<REDACTED>"
Note: switching to '<REDACTED>.

  </pre>
</details>

### Steps to reproduce

1. Run any build with tags using `git-clone` step `4.1.0`
2. use [Generate changelog](https://github.com/bitrise-steplib/steps-generate-changelog) step

**Comment by godrei** [comment] 2021-03-17 11:19
Hi @jamie1192 ,
sorry for the inconvenience!

It seems you are affected by the changes we applied in version [4.0.28](https://github.com/bitrise-steplib/steps-git-clone/releases/tag/4.0.28).

In that version, we limited `git fetch` calls to the given branch **for commit checkout**.  With this change in the case of commit checkout we do not fetch any tags, I can confirm. That's why the generate-changelog step generates the changelog from the initial commit till the actual commit. 

Other checkout strategies were already fetching by specifying the `branch` as refspec, you can spot it in the [unit test changes of version 4.0.28](https://github.com/bitrise-steplib/steps-git-clone/commit/9ccf0391564600b855cc32165a5e855a1bb1104d#diff-138c746f49bf0ff30f777d7e2e4b67e3facd93e3a4343c1ff4b4e593d507ae88).

Since all the other checkout strategies are behaving this way, we considered the deviance of the commit checkout as a bug. A bug that affects users in a way that the step runs longer than it could, **in the case of a commit checkout**.

The feature you relied on was unintentional unfortunately, the step's opinion is that changelog generation happens when you trigger the Step by a git tag. In this case, [the step uses the `--tags` flag](https://github.com/bitrise-steplib/steps-git-clone/blob/master/gitclone/checkout.go#L211-L212) for git fetch calls, to make sure tags are available for changelog generation.

This issue highlights that the opinionated tag handling behavior is not ideal, we would like to fix this by introducing explicit control over tag fetching. You can see the suggested solution in this PR: https://github.com/bitrise-steplib/steps-git-clone/pull/144

The PR introduces a new input `fetch_tags`:

```
  - fetch_tags: automatic
     opts:
       category: Clone Config
       title: Should the step fetch tags?
       descriptions: |-
         automatic - fetches all tags from the remote in case of a tag checkout, otherwise fetches tags that point at objects that are downloaded from the remote repository
         yes - fetches all the tags
         no - does not fetch any tags
       value_options:
       - "automatic"
       - "yes"
       - "no"
```

With this new input you can entirely turn off tag fetching to speed up the step, or you can opt-in tag fetching, so you can generate a changelog based on git tags.

**Comment by jamie1192** [comment] 2021-03-17 22:29
Hi @godrei , thanks for the detailed response.

That seems reasonable, will be sticking to `4.0.26` for the time being and dealing with the slightly longer build times until that PR is merged and the step is updated then. 

Thanks!

**Comment by godrei** [comment] 2021-03-25 08:12
Hi @jamie1192 ,
a new major version released with the tag fetch control, see the Release Notes: https://github.com/bitrise-steplib/steps-git-clone/releases/tag/5.0.0.

I'll close this issue, but if you need more info/help just let us know by opening a new one!

**Closed by godrei** 2021-03-25 08:12 UTC
