### ISSUE TITLE
Git Clone Repository (exit code: 1) 

### ISSUE THREAD

**Issue by sciasxp** [bitrise-steplib/steps-git-clone#94] opened 2019-05-30 18:42 UTC
Even though I am connecting to bitbucket with an Administrator account it fails to add the ssh automatically. So, I end up trying to provide my own ssh public/private keys, but I always get an error on trying to fetch the repository.

Bellow is my logging:

Agent version:	1.4.0
Start time:	2019-05-30T18:28:04Z
$ docker "run" "-v" "/var/run/docker.sock:/var/run/docker.sock" "-v" "/bitrise:/bitrise" "-v" "/tmp/bitrise-agent286384991:/.bitrise-config" "--privileged" "--network=host" "--name=bitrise-main-container" "bitriseio/android:pinned" "bitrise" "run" "--config" "/.bitrise-config/bitrise.yml" "--inventory" "/.bitrise-config/bitrise.secrets.yml" "--json-params-base64" "eyJ3b3JrZmxvdyI6InZhbGlkYXRpb25fd29ya2Zsb3dfd2l0aF9zc2gifQ=="

  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝

  version: 1.30.0

INFO[18:28:05] bitrise runs in Secret Filtering mode 
INFO[18:28:05] bitrise runs in CI mode           
INFO[18:28:05] Running workflow: validation_workflow_with_ssh 

Switching to workflow: validation_workflow_with_ssh

+------------------------------------------------------------------------------+
| (0) Activate App SSH key                                                     |
+------------------------------------------------------------------------------+
| id: activate-ssh-key                                                         |
| version: 3.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2019-05-30T18:28:06Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[18:28:06] Start installing (expect) with apt-get       
INFO[18:28:06]  * [OK] Step dependency (expect) installed, available. 
INFO[18:28:06] Start installing (git) with apt-get          
INFO[18:28:06]  * [OK] Step dependency (git) installed, available. 

# Configuration

* Path to save the RSA SSH private key: */root/.ssh/steplib_ssh_step_id_rsa*
* Should remove other identities from the ssh-agent? *true*
-> $ mkdir -p /root/.ssh
-> $ chmod 0600 /root/.ssh/steplib_ssh_step_id_rsa
Could not open a connection to your authentication agent.
 (i) ssh_agent_check_result: 2
 (i) ssh-agent not started
 (i) starting a new ssh-agent and exporting connection information with envman
Agent pid 243
 (i) Expose SSH_AUTH_SOCK for the new ssh-agent, with envman
spawn ssh-add /root/.ssh/steplib_ssh_step_id_rsa
Identity added: /root/.ssh/steplib_ssh_step_id_rsa (/root/.ssh/steplib_ssh_step_id_rsa)

# Success

The SSH key was saved to */root/.ssh/steplib_ssh_step_id_rsa*
and was successfully added to ssh-agent.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 1.59 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.1.1 -> 4.0.3                                             |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (1) Git Clone Repository                                                     |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 3.4.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-05-30T18:28:08Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[18:28:08] Start installing (golang) with apt-get       
INFO[18:28:08]  * [OK] Step dependency (go) installed, available. 

Git Clone Configs:
- CloneIntoDir: /bitrise/src
- RepositoryURL: [REDACTED]
Git Checkout Configs:
- Commit: 
- Tag: 
- Branch: [REDACTED]
- CloneDepth: 
Git Pull Request Configs:
- PullRequestURI: 
- PullRequestID: 
- BranchDest: 
- PullRequestMergeBranch: 
- ResetRepository: No
Bitrise Build Configs:
- BuildURL: 
- BuildAPIToken: 

Git clone repository
=> git "init"
=> git "remote" "add" "origin" "[REDACTED]"
=> git "fetch"
0 attempt failed:
Warning: Permanently added 'bitbucket.org,18.205.93.0' (RSA) to the list of known hosts.
An unexpected error occurred
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
1 attempt failed:
invalid repository syntax.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
2 attempt failed:
An unexpected error occurred
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed, error: An unexpected error occurred
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 5.17 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.14                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+

                                          ▼

INFO[18:28:12] Step uses latest version -- Updating StepLib ... 
INFO[18:28:12] Update StepLib (https://github.com/bitrise-io/bitrise-steplib.git)... 
+------------------------------------------------------------------------------+
| (2) Running project scanner                                                  |
+------------------------------------------------------------------------------+
WARN[18:28:16] A previous step failed, and this step (Running project scanner) was not marked as IsAlwaysRun, skipped 
| id: project-scanner                                                          |
| version: 3.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-05-30T18:28:16Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
|                                                                              |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 4.29 sec |
+---+---------------------------------------------------------------+----------+

+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 1.59 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.1.1 -> 4.0.3                                             |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 5.17 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.14                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 4.29 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 11 sec                                                        |
+------------------------------------------------------------------------------+

Outdated analytics plugin, used format version is lower then host bitrise-cli's format version, please update the plugin

Submitting anonymized usage informations...
For more information visit:
https://github.com/bitrise-io/bitrise-plugins-analytics/blob/master/README.md

**Comment by fehersanyi-bitrise** [comment] 2019-06-03 07:23
Hello @sciasxp 

Is this the SSH key bitrise set up or a manually set up key?
if the later, did you do it this way? https://devcenter.bitrise.io/getting-started/adding-a-new-app/setting-up-ssh-keys/#manual-setup

**Comment by dipkasyap** [comment] 2019-11-18 23:54
@fehersanyi-bitrise  I am having the same issue `git-clone@4.0.17 (exit code: 1)`, I did configure as you mentioned

**Comment by dipkasyap** [comment] 2019-11-24 23:46
On my case there was some issue with bitbucket, it was not saving the SSH properly now its good.

**Comment by lpusok** [comment] 2021-03-16 10:48
Closing as it was resolved, most probably caused by temporary BitBucket outage.

**Closed by lpusok** 2021-03-16 10:48 UTC
