### ISSUE TITLE
Validation Failed

### ISSUE THREAD

**Issue by AhsanKhan231** [bitrise-steplib/steps-git-clone#93] opened 2019-05-30 07:41 UTC
I have added the ssh key bitrise provided in my bitbucket account on this path (https://bitbucket.org/account/user/username) but still when i scan on bitrise, it give me this error. What's the issue actually. I followed the step by step tutorials on bitrise.

Agent version:	1.4.0
Start time:	2019-05-30T07:30:18Z
$ docker "run" "-v" "/var/run/docker.sock:/var/run/docker.sock" "-v" "/bitrise:/bitrise" "-v" "/tmp/bitrise-agent009789165:/.bitrise-config" "--privileged" "--network=host" "--name=bitrise-main-container" "bitriseio/android:pinned" "bitrise" "run" "--config" "/.bitrise-config/bitrise.yml" "--inventory" "/.bitrise-config/bitrise.secrets.yml" "--json-params-base64" "eyJ3b3JrZmxvdyI6InZhbGlkYXRpb25fd29ya2Zsb3dfd2l0aF9zc2gifQ=="

  ██████╗ ██╗████████╗██████╗ ██╗███████╗███████╗
  ██╔══██╗██║╚══██╔══╝██╔══██╗██║██╔════╝██╔════╝
  ██████╔╝██║   ██║   ██████╔╝██║███████╗█████╗
  ██╔══██╗██║   ██║   ██╔══██╗██║╚════██║██╔══╝
  ██████╔╝██║   ██║   ██║  ██║██║███████║███████╗
  ╚═════╝ ╚═╝   ╚═╝   ╚═╝  ╚═╝╚═╝╚══════╝╚══════╝

  version: 1.30.0

INFO[07:30:19] bitrise runs in Secret Filtering mode 
INFO[07:30:19] bitrise runs in CI mode           
INFO[07:30:19] Running workflow: validation_workflow_with_ssh 

Switching to workflow: validation_workflow_with_ssh

+------------------------------------------------------------------------------+
| (0) Activate App SSH key                                                     |
+------------------------------------------------------------------------------+
| id: activate-ssh-key                                                         |
| version: 3.1.1                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2019-05-30T07:30:21Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[07:30:21] Start installing (expect) with apt-get       
INFO[07:30:21]  * [OK] Step dependency (expect) installed, available. 
INFO[07:30:21] Start installing (git) with apt-get          
INFO[07:30:21]  * [OK] Step dependency (git) installed, available. 

# Configuration

* Path to save the RSA SSH private key: */root/.ssh/steplib_ssh_step_id_rsa*
* Should remove other identities from the ssh-agent? *true*
-> $ mkdir -p /root/.ssh
-> $ chmod 0600 /root/.ssh/steplib_ssh_step_id_rsa
Could not open a connection to your authentication agent.
 (i) ssh_agent_check_result: 2
 (i) ssh-agent not started
 (i) starting a new ssh-agent and exporting connection information with envman
Agent pid 241
 (i) Expose SSH_AUTH_SOCK for the new ssh-agent, with envman
spawn ssh-add /root/.ssh/steplib_ssh_step_id_rsa
Identity added: /root/.ssh/steplib_ssh_step_id_rsa (/root/.ssh/steplib_ssh_step_id_rsa)

# Success

The SSH key was saved to */root/.ssh/steplib_ssh_step_id_rsa*
and was successfully added to ssh-agent.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 1.89 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.1.1 -> 4.0.3                                             |
+---+---------------------------------------------------------------+----------+

                                          ▼

+------------------------------------------------------------------------------+
| (1) Git Clone Repository                                                     |
+------------------------------------------------------------------------------+
| id: git-clone                                                                |
| version: 3.4.3                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-05-30T07:30:22Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[07:30:22] Start installing (golang) with apt-get       
INFO[07:30:22]  * [OK] Step dependency (go) installed, available. 

Git Clone Configs:
- CloneIntoDir: /bitrise/src
- RepositoryURL: [REDACTED]
Git Checkout Configs:
- Commit: 
- Tag: 
- Branch: [REDACTED]
- CloneDepth: 
Git Pull Request Configs:
- PullRequestURI: 
- PullRequestID: 
- BranchDest: 
- PullRequestMergeBranch: 
- ResetRepository: No
Bitrise Build Configs:
- BuildURL: 
- BuildAPIToken: 

Git clone repository
=> git "init"
=> git "remote" "add" "origin" "[REDACTED]"
=> git "fetch"
0 attempt failed:
Warning: Permanently added 'bitbucket.org,18.205.93.1' (RSA) to the list of known hosts.
An unexpected error occurred
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
1 attempt failed:
An unexpected error occurred
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Retrying...
=> git "fetch"
2 attempt failed:
invalid repository syntax.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Failed, error: invalid repository syntax.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 6.28 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.14                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+

                                          ▼

INFO[07:30:27] Step uses latest version -- Updating StepLib ... 
INFO[07:30:27] Update StepLib (https://github.com/bitrise-io/bitrise-steplib.git)... 
+------------------------------------------------------------------------------+
| (2) Running project scanner                                                  |
+------------------------------------------------------------------------------+
| id: project-scanner                                                          |
| version: 3.1.0                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2019-05-30T07:30:33Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
WARN[07:30:33] A previous step failed, and this step (Running project scanner) was not marked as IsAlwaysRun, skipped 
|                                                                              |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 5.27 sec |
+---+---------------------------------------------------------------+----------+

+------------------------------------------------------------------------------+
|                               bitrise summary                                |
+---+---------------------------------------------------------------+----------+
|   | title                                                         | time (s) |
+---+---------------------------------------------------------------+----------+
| ✓ | Activate App SSH key                                          | 1.89 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.1.1 -> 4.0.3                                             |
+---+---------------------------------------------------------------+----------+
| x | Git Clone Repository (exit code: 1)                           | 6.28 sec |
+---+---------------------------------------------------------------+----------+
| Update available: 3.4.3 -> 4.0.14                                            |
| Issue tracker: https://github.com/bitrise-io/steps-git-clone/issues          |
| Source: https://github.com/bitrise-io/steps-git-clone                        |
+---+---------------------------------------------------------------+----------+
| - | Running project scanner                                       | 5.27 sec |
+---+---------------------------------------------------------------+----------+
| Total runtime: 13 sec                                                        |
+------------------------------------------------------------------------------+

Outdated analytics plugin, used format version is lower then host bitrise-cli's format version, please update the plugin

Submitting anonymized usage informations...
For more information visit:
https://github.com/bitrise-io/bitrise-plugins-analytics/blob/master/README.md

**Comment by bitce** [comment] 2019-05-30 10:11
Hi @AhsanKhan231! Is there a reason you are adding an SSH key manually? Have you tried simply connecting your Bitbucket account and selecting your repository from the list, allowing Bitrise to do this manually?

**Comment by AhsanKhan231** [comment] 2019-05-30 10:15
Yes. I am doing this manually . Screenshot is attached
![Capture](https://user-images.githubusercontent.com/32359393/58626275-cfff8400-82ed-11e9-90f5-be94afb77f1d.PNG)

**Comment by bitce** [comment] 2019-05-30 10:18
I understand, I am asking what is the reason for this?

**Comment by bitce** [comment] 2019-05-30 10:23
Thanks for reporting! I could recreate the issue, we're looking into it.

**Comment by lpusok** [comment] 2021-03-16 10:47
Closing as it was resolved, most probably caused by temporary BitBucket outage.

**Closed by lpusok** 2021-03-16 10:47 UTC
